## 1. DataTypes & Attributes
- axis=0 => Dimensions
- axis=1 => Rows
- axis=2 => Columns

In [1]:
# Import numpy
import numpy as np

In [13]:
# Numpy's main datatypes is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [31]:
# numpy 2 dimension
a2 = np.array([[1, 2.2,3],
              [4.7, 5, 6]])
a2

array([[1. , 2.2, 3. ],
       [4.7, 5. , 6. ]])

In [15]:
# numpy 3 dimension
a3 = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
              [10, 11, 12]],
              [[13, 14, 15],
              [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [21]:
"""
Dimension = 1
Row = 1
Columns = 3
"""
a1.shape

(3,)

In [27]:
"""
Dimension = 2
Row = 2
Columns = 3
"""
a2.shape

(2, 3)

In [25]:
"""
Dimensions = 3
Row = 2
Columns = 3
"""
a3.shape

(3, 2, 3)

In [28]:
# to see array dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [32]:
# to check the data type of an array
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [34]:
# to check the total number of elements in an array
a1.size, a2.size, a3.size

(3, 6, 18)

In [36]:
# Create DataFrame from a NumPy
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.2  3.0
1  4.7  5.0  6.0

## 2. Creating Arrays

In [55]:
# Create numpy array with 1
ones = np.ones((2, 3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
# Create numpy array with 0
zeros = np.zeros((2, 3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

- .ones & .zeros to make a tamplate

In [45]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
random_array = np.random.randint(5, 10, size=(2, 5))
random_array

array([[5, 7, 9, 6, 7],
       [5, 9, 7, 6, 5]], dtype=int32)

In [48]:
random_array.shape

(2, 5)

In [49]:
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.30215841, 0.83635079, 0.29647501, 0.02225029, 0.97832569],
       [0.45124492, 0.09336053, 0.66479159, 0.3764266 , 0.75983766],
       [0.45424693, 0.49662297, 0.0092727 , 0.6532922 , 0.40259121]])

In [50]:
random_array_2.shape

(3, 5)

In [57]:
random_array_3 = np.random.rand(3, 2, 3)
random_array_3

array([[[9.24673181e-01, 5.96076892e-01, 5.66777264e-01],
        [3.74945033e-01, 6.97289589e-01, 9.33694015e-01]],

       [[4.93707346e-01, 7.78325240e-02, 7.18600213e-01],
        [3.94736636e-01, 3.73635458e-01, 1.98752114e-01]],

       [[8.88105035e-04, 6.52682139e-01, 2.90311795e-01],
        [4.47671935e-01, 2.44760802e-02, 3.85866106e-01]]])

In [108]:
# Mengatur agar angka tetap sama / tidak berubah
np.random.seed(42)
random_array_4 = np.random.randint(0, 10, size=(3, 2))
random_array_4

array([[6, 3],
       [7, 4],
       [6, 9]], dtype=int32)

## Viewing arrays & metric

In [116]:
np.random.seed(42)
random_array_5 = np.random.randint(5, 15, size=(3 , 3, 3))
random_array_5

array([[[11,  8, 12],
        [ 9, 11, 14],
        [ 7, 11, 12]],

       [[ 9,  8, 12],
        [12,  7, 10],
        [ 9,  6, 12]],

       [[10,  6,  9],
        [ 5, 14, 10],
        [13,  5, 14]]], dtype=int32)

In [117]:
np.unique(random_array_5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int32)

In [126]:
random_array_5[2:3, 1:2, 1:2]

array([[[14]]], dtype=int32)

In [132]:
# Create array 4 Dimension
random_array_6 = np.random.randint(0, 10, size=(3, 4, 3, 2))
random_array_6

array([[[[4, 3],
         [1, 3],
         [9, 9]],

        [[2, 9],
         [0, 7],
         [4, 3]],

        [[7, 6],
         [1, 0],
         [3, 7]],

        [[1, 2],
         [0, 0],
         [2, 4]]],


       [[[2, 0],
         [0, 7],
         [9, 1]],

        [[2, 1],
         [2, 6],
         [0, 9]],

        [[7, 9],
         [9, 9],
         [1, 2]],

        [[8, 6],
         [3, 9],
         [4, 1]]],


       [[[7, 3],
         [8, 4],
         [8, 3]],

        [[9, 4],
         [8, 7],
         [2, 0]],

        [[2, 3],
         [1, 0],
         [6, 7]],

        [[6, 4],
         [0, 6],
         [6, 8]]]], dtype=int32)

In [128]:
random_array_6.shape

(5, 4, 3, 2)