# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [40]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [14]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((3, 1, 3), 3, dtype('int64'), 9, numpy.ndarray)

In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [26]:
# Create an array of shape (10, 2) with only ones
arr3 = np.ones((10, 2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
# Create an array of shape (7, 2, 3) of only zeros
arr4 = np.zeros((7, 2, 3))
arr4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
# Create an array within a range of 0 and 100 with step 3
arr5 = np.arange(0, 100, 3)
arr5

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr6 = np.random.randint(0, 10, size=(7, 2))
arr6

array([[8, 0],
       [2, 2],
       [4, 6],
       [5, 2],
       [3, 3],
       [4, 9],
       [5, 1]], dtype=int32)

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr7 = np.random.random_sample(size=(3, 5))
arr7

array([[0.5554432 , 0.28879918, 0.27113435, 0.43179673, 0.31480525],
       [0.60060243, 0.33673323, 0.11714941, 0.13881906, 0.72438791],
       [0.73812902, 0.69245167, 0.13176413, 0.17727773, 0.21429567]])

In [38]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr8 = np.random.randint(0, 10, size=(4, 6))
arr8

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr9 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(arr9)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [50]:
# Find the 0'th index of the latest array you created
arr9[:1, :1]

array([[9]], dtype=int32)

In [54]:
# Get the first 2 rows of latest array you created
arr9[1:2, :1]

array([[5]], dtype=int32)

In [55]:
# Get the first 2 values of the first 2 rows of the latest array
arr9[1:2, :2]

array([[5, 3]], dtype=int32)

In [71]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(42)
arr10 = np.random.randint(0, 10, size=(3, 5))
arr11 = np.ones((3, 5))

In [72]:
# Add the two arrays together
np.add(arr10, arr11)

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [73]:
# Create another array of ones of shape (5, 3)
arr12 = np.ones((5, 3))
arr12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
# Try add the array of ones and the other most recent array together
arr12 + arr12

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [78]:
# Create another array of ones of shape (3, 5)
arr13 = np.ones((3, 5))
arr13

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [79]:
# Subtract the new array of ones from the other most recent array
np.subtract(arr13, arr11)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
# Multiply the ones array with the latest array
np.multiply(arr13, arr11)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
# Take the latest array to the power of 2 using '**'
np.power(arr10, 2)

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [85]:
# Do the same thing with np.square()
np.square(arr10)

array([[36,  9, 49, 16, 36],
       [81,  4, 36, 49, 16],
       [ 9, 49, 49,  4, 25]], dtype=int32)

In [86]:
# Find the mean of the latest array using np.mean()
np.mean(arr10)

np.float64(5.2)

In [87]:
# Find the maximum of the latest array using np.max()
np.max(arr10)

np.int32(9)

In [88]:
# Find the minimum of the latest array using np.min()
np.min(arr10)

np.int32(2)

In [89]:
# Find the standard deviation of the latest array
np.std(arr10)

np.float64(2.039607805437114)

In [90]:
# Find the variance of the latest array
np.var(arr10)

np.float64(4.160000000000001)

In [93]:
# Reshape the latest array to (3, 5, 1)
arr13.reshape(3, 5, 1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [94]:
# Transpose the latest array
arr13.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [101]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(42)
arr14 = np.random.randint(0, 10, size=(3, 3))
arr15 = np.random.randint(0, 10, size=(3, 2))

In [102]:
# Perform a dot product on the two newest arrays you created
np.dot(arr14, arr15)

array([[59, 74],
       [76, 99],
       [64, 83]], dtype=int32)

In [105]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr16 = np.random.randint(0, 10, size=(4, 3))
arr17 =np.random.randint(0, 10, size=(4, 3))
arr16.shape, arr17.shape

((4, 3), (4, 3))

In [106]:
# Perform a dot product on the two newest arrays you created
np.dot(arr16, arr17)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr16, arr17.T)

array([[161,  62,  79,  88],
       [131,  92,  73,  82],
       [160,  80, 113, 113],
       [ 97,  74,  36,  49]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [127]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(42)
arr18 = np.random.randint(0, 10, size=(3, 3))
arr19 = np.random.randint(0, 10, size=(3, 3))
arr18, arr19

(array([[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7]], dtype=int32),
 array([[4, 3, 7],
        [7, 2, 5],
        [4, 1, 7]], dtype=int32))

In [128]:
# Compare the two arrays with '>'
arr18 > arr19

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [129]:
# Compare the two arrays with '>='
arr18 >= arr19

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [130]:
# Find which elements of the first array are greater than 7
arr18 > 7

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [131]:
# Which parts of each array are equal? (try using '==')
arr18 == arr19

array([[False,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [132]:
# Sort one of the arrays you just created in ascending order
np.sort(arr19)

array([[3, 4, 7],
       [2, 5, 7],
       [1, 4, 7]], dtype=int32)

In [133]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr19)

array([[1, 0, 2],
       [1, 2, 0],
       [1, 0, 2]])

In [134]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr19)

np.int64(2)

In [135]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr19)

np.int64(7)

In [136]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr19, axis=1)

array([2, 0, 2])

In [137]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr19, axis=0)

array([0, 2, 1])

In [138]:
# Create an array of normally distributed random numbers
arr20 = np.random.randint(0, 10, size=(3, 3))
arr20

array([[5, 1, 4],
       [0, 9, 5],
       [8, 0, 9]], dtype=int32)

In [140]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr21 = np.arange(0, 110, 10)
arr21

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.